spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    # User database
    user:
      url:  jdbc:h2:mem:user_database
      # Product database
    product:
      url:  jdbc:h2:mem:product_database
      # Order database
    order:
      url:  jdbc:h2:mem:order_database