version: "3"
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test_db'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  app:
    image: springboot/spring-boot-reactive-r2dbc
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
